OSRelease: 13
OSName: queens
NuageMajorRelease: 5
NuageMinorRelease: 3
NuageUpdateRelease: 3
NuageRelease: 1
RepoBaseUrl: https://s3-us-west-1.amazonaws.com/nuage-public-mirror/574d63bb0727c27e014d8f27ccc275c3f9641b955e8aa7659d74e4df9cf7847a/5.3.3/queens/
