OSRelease: 16
OSMinorRelease: 1.6
OSNamespace: rhosp-rhel8
OSName: train
UseOvn: yes
RHRegistry: registry.redhat.io
NuageMajorRelease: 20
NuageMinorRelease: 10
NuageUpdateRelease: 5
NuageRelease: 1
RepoBaseUrl: https://s3-us-west-1.amazonaws.com/nuage-public-mirror/574d63bb0727c27e014d8f27ccc275c3f9641b955e8aa7659d74e4df9cf7847a/20.10.5/train
NuageUpgradeScripts: nuage-openstack-upgrade-20.10.5-296.tar.gz
DockerImages:
  - heat-api-cfn
  - heat-api
  - heat-engine
  - horizon
  - neutron-server
  - neutron-openvswitch-agent
  - nova-compute
