OSRelease: 16
OSMinorRelease: 1
OSNamespace: rhosp-rhel8
OSName: train
RHRegistry: registry.redhat.io
NuageMajorRelease: 20
NuageMinorRelease: 5
NuageUpdateRelease: 2
NuageRelease: 1
RepoBaseUrl: https://s3-us-west-1.amazonaws.com/nuage-public-mirror/574d63bb0727c27e014d8f27ccc275c3f9641b955e8aa7659d74e4df9cf7847a/20.5.2/train
NuageUpgradeScripts: nuage-openstack-upgrade-20.5.2-28.tar.gz
